apiVersion: v1
kind: Service
metadata:
  name: book-db-svc-1
  namespace: {{ .Values.environment.env }}
spec:
  selector:
    app: book-db-1
  ports:
  - port: 3307
    targetPort: 3306
    nodePort: 30002
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
