apiVersion: v1
kind: Service
metadata:
  name: book-frontend-svc-1
  namespace: {{ .Values.environment.env }}
spec:
  selector:
    app: book-frontend-1
  ports:
  - port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.service.frontend.targetPort }}
    nodePort: {{ .Values.service.frontend.nodePort }}
  type: {{ .Values.service.frontend.type }}
  externalTrafficPolicy: Local
