apiVersion: v1
kind: Service
metadata:
  name: book-frontend-svc-1
  namespace: {{ .Values.environment.env }}
spec:
  selector:
    app: book-frontend-1
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    nodePort: 30002
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
