apiVersion: v1
kind: Service
metadata:
  name: book-backend-svc-1
  namespace: {{ .Values.environment.env }}
spec:
  selector:
    # app: book-backend
    # type: book-backend-1
    ver: book-backend-1
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30003
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local