apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: {{ .Values.environment.env }}
  name: book-frontend-replicas
spec:
  replicas: 1
  selector:
    matchLabels:
      # ver: book-frontend-1
      app: book-frontend-1
  template:
    metadata:
      name: book-frontend-1
      labels:
        # ver: book-frontend-1
        app: book-frontend-1
      namespace: {{ .Values.environment.env }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node2
      containers:
      - name: container
        image: dannielkil/book-frontend
        # ports:
        # - containerPort: 80
      terminationGracePeriodSeconds: 0