apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: {{ .Values.environment.env }}
  name: book-backend-replicas
spec:
  replicas: 1
  selector:
    matchLabels:
      ver: book-backend-1
  template:
    metadata:
      name: book-backend-1
      labels:
        ver: book-backend-1
      namespace: {{ .Values.environment.env }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node2
      containers:
      - name: container
        image: dannielkil/book-backend
        # ports:
        # - containerPort: 8080
      terminationGracePeriodSeconds: 0