apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: book-dev
  name: book-db-replicas
spec:
  replicas: 1
  selector:
    matchLabels:
      # ver: book-db-1
      app: book-db-1
  template:
    metadata:
      name: book-db-1
      labels:
        # ver: book-db-1
        app: book-db-1
      namespace: book-dev
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node2
      containers:
      - name: container
        image: dannielkil/book-db
        # ports:
        # - containerPort: 3306
      terminationGracePeriodSeconds: 0