apiVersion: v1
kind: Service
metadata:
  name: book-db-svc-1
spec:
  selector:
    app: book-db
  ports:
  - port: 3307
    targetPort: 3306
    nodePort: 30002
  type: NodePort
  externalTrafficPolicy: Local
