apiVersion: v1
kind: Service
metadata:
  name: book-frontend-svc-1
spec:
  selector:
    app: book-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  type: NodePort
  externalTrafficPolicy: Local
