apiVersion: v1
kind: Service
metadata:
  name: book-backend-svc-1
spec:
  selector:
    # app: book-backend
    type: book-backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30003
  type: NodePort
  externalTrafficPolicy: Local
