apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: {{ .Values.environment.env }}
  name: book-db-replicas
spec:
  replicas: 1
  selector:
    matchLabels:
      # ver: book-db-1
      app: book-db-1
  template:
    metadata:
      name: book-db-1
      labels:
        # ver: book-db-1
        app: book-db-1
      namespace: {{ .Values.environment.env }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node2
      containers:
      - name: container
        image: dannielkil/book-db
        # ports:
        # - containerPort: 3306
        livenessProbe:
          tcpSocket:
            port: 3306
          # httpGet:                # HttpGet 메소드로 점검
          #   path: /               # 체크할 경로
          #   port: 3306            # 체크할 Port
          initialDelaySeconds: 5  # 최초 5초 후에 LivenessProbe 체크를 시작함
          periodSeconds: 10       # 10초마다 LivenessProbe 체크
          timeoutSeconds: 1       # 
          successThreshold: 1     # 1번만 성공해도 파드가 정상적으로 실행됐다고 판단
          failureThreshold: 3     # 3번 실패 시 Pod Restart
      terminationGracePeriodSeconds: 0